services:
  placeholder-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
