// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/placeholder": {
            "get": {
                "description": "Generates a placeholder image with specified dimensions, text, and colors. The image size is limited to a maximum of 1000x1000 pixels.",
                "produces": [
                    "image/png"
                ],
                "summary": "Generate a placeholder image",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 400,
                        "description": "Width of the image (max 1920)",
                        "name": "w",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 300,
                        "description": "Height of the image (max 1920)",
                        "name": "h",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "Placeholder",
                        "description": "Text to display",
                        "name": "text",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Font size of the text",
                        "name": "font_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "FFFFFF00",
                        "description": "Background color in 8-character hex format without '#'. The last 2 characters represent alpha (transparency)",
                        "name": "bg_color",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "000000FF",
                        "description": "Font color in 8-character hex format without '#'. The last 2 characters represent alpha (transparency)",
                        "name": "font_color",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The generated placeholder image",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid input parameters or image too large",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error, failed to generate image or encode it",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Placeholder API",
	Description:      "This is an API to generate placeholder images.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
