basePath: /
info:
  contact: {}
  description: This is an API to generate placeholder images.
  title: Placeholder API
  version: "1.0"
paths:
  /placeholder:
    get:
      description: Generates a placeholder image with specified dimensions, text,
        and colors. The image size is limited to a maximum of 1000x1000 pixels.
      parameters:
      - default: 400
        description: Width of the image (max 1920)
        in: query
        name: width
        type: integer
      - default: 300
        description: Height of the image (max 1920)
        in: query
        name: height
        type: integer
      - default: Placeholder
        description: Text to display
        in: query
        name: text
        type: string
      - description: Font size of the text
        in: query
        name: font_size
        type: number
      - default: '#FFFFFF'
        description: Background color in hex format
        in: query
        name: bg_color
        type: string
      - default: '#000000'
        description: Font color in hex format
        in: query
        name: font_color
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: The generated placeholder image
          schema:
            type: file
        "400":
          description: Invalid input parameters or image too large
          schema:
            type: string
        "500":
          description: Internal server error, failed to generate image or encode it
          schema:
            type: string
      summary: Generate a placeholder image
swagger: "2.0"
